trainer:
  name: "default"
  params:
    max_epochs: 5
    accelerator: cpu
    devices: 1
    limit_train_batches: 128
    log_every_n_steps: 10
    precision: bf16-mixed
    num_sanity_val_steps: 1
    enable_checkpointing: true
